version: '3.8'

services:
  aso-tool:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - ENVIRONMENT=production
      - DEBUG=0
    restart: unless-stopped