services:
  - type: web
    name: aso-tool
    env: python
    runtime: python3.11
    buildCommand: |
      pip install -e .
      python -c "import nltk; nltk.download('punkt'); nltk.download('vader_lexicon')"
    startCommand: python -m uvicorn aso_tool.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: NLTK_DATA
        value: /opt/render/project/src/nltk_data
      - key: PYTHON_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true