services:
  - type: web
    name: aso-tool
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 20.11.1
      - key: PATH
        value: /opt/render/project/src/nodejs/bin:$PATH
    healthCheckPath: /api/health