services:
  - type: web
    name: aso-tool
    env: python
    runtime: python3.11
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt'); nltk.download('vader_lexicon')"
      mkdir -p src/app/static
    startCommand: cd src && python wsgi.py
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src/src
      - key: NLTK_DATA
        value: /opt/render/nltk_data
      - key: STATIC_DIR
        value: /opt/render/project/src/src/app/static
    healthCheckPath: /health
    autoDeploy: true