services:
  - type: web
    name: aso-tool
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "import nltk; nltk.download('punkt'); nltk.download('vader_lexicon')"
    startCommand: cd app && PYTHONPATH=/app python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: /app
    healthCheckPath: /health
    autoDeploy: true