services:
  - type: web
    name: aso-tool
    env: python
    runtime: python3.11
    buildCommand: |
      # Update pip and install build tools
      python -m pip install --upgrade pip
      pip install wheel setuptools

      # Install the package in editable mode
      pip install -e .

      # Install NLTK data
      python -c "import nltk; nltk.download('punkt'); nltk.download('vader_lexicon')"

      # Create necessary directories
      mkdir -p static
      mkdir -p data

    startCommand: |
      cd /opt/render/project/src && \
      gunicorn -c gunicorn_config.py 'src.app.main:app'

    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: NLTK_DATA
        value: /opt/render/project/src/data
      - key: STATIC_DIR
        value: /opt/render/project/src/static
      - key: PYTHON_ENV
        value: production
      - key: LOG_LEVEL
        value: info

    healthCheckPath: /health
    autoDeploy: true