version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=aso_tool

  backend:
    build:
      context: ..
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/aso_tool
    depends_on:
      - mongodb
    volumes:
      - ../backend:/app/backend
      - ../tests:/app/tests

volumes:
  mongodb_data: